set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
find_program(ARM_GCC arm-none-eabi-gcc HINTS "$ENV{ARM_GCC_PATH}/bin" REQUIRED)
get_filename_component(ARM_BIN "${ARM_GCC}" DIRECTORY)
set(CMAKE_C_COMPILER "${ARM_GCC}")
set(CMAKE_ASM_COMPILER "${ARM_GCC}")
find_program(CMAKE_OBJCOPY arm-none-eabi-objcopy HINTS "${ARM_BIN}" REQUIRED)
find_program(CMAKE_SIZE arm-none-eabi-size HINTS "${ARM_BIN}" REQUIRED)
