#ifndef UAV_BOARD_H
#define UAV_BOARD_H
#define UAV_PWM_TIMER htim1
#define UAV_PWM_CHANNELS {TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4}
#define UAV_PWM_STOP_US 1000
#define UAV_PWM_MAX_US 2000
#define BMI088_SPI hspi2
#define BMI088_ACC_GPIOx GPIOE
#define BMI088_ACC_GPIOp GPIO_PIN_15
#define BMI088_GYRO_GPIOx GPIOD
#define BMI088_GYRO_GPIOp GPIO_PIN_8
#define UAV_KEY_PORT GPIOD
#define UAV_KEY1_PIN GPIO_PIN_0
#define UAV_KEY2_PIN GPIO_PIN_1
#define UAV_LED_PORT GPIOE
#define UAV_HEATER_TIMER htim10
#endif
